platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk
inputs:
- name: https-only-tests-master
- name: output-https-only-tests-master-deploy
run:
  path: https-only-tests-master/ci/check.sh
outputs: # convention: output-<repoName>-<taskname>
  # creates a dir in the docker-image to pass on files of this task to next ones
- name: output-https-only-tests-master-check
