#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

management:
    endpoints:
        prometheus:
            enabled: true
        web:
            exposure:
                include: health,info,prometheus